config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "posts#index"
  resources :posts

  namespace :home do
    get "about", as: 'about'
    get "terms", as: 'terms'
    get "privacy", as: 'privacy'
  end
  
  resources :posts do
    post "select_best_comment", :to => "posts#select_best_comment", as: 'select_best_comment'
    resources :comments,only: [:new, :create, :edit, :update] do
      patch "delete", :to => "comments#delete", as: 'delete'
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
  end

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :omniauth_callbacks => 'users/omniauth_callbacks',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  namespace :users do
    get ":id/profile", :to => "profiles#show", as: 'profile'
    get ":id/profile/edit", :to => "profiles#edit", as: 'edit_profile'
    patch ":id/profile/update", :to => "profiles#update", as: 'update_profile'
    get ":id/profile/posts_show", :to => "profiles#posts_show", as: 'posts_show'
    get ":id/profile/favorite_comments_show", :to => "profiles#favorite_comments_show", as: 'favorite_comments_show'
    get ":id/profile/best_comments_show", :to => "profiles#best_comments_show", as: 'best_comments_show'
  end

  get "inquiry_mailer/new", :to => "inquiry_mailer#new", as: 'new_inquiry_mailer'
  get "inquiry_mailer/confirm",:to => "inquiry_mailer#confirm",as: 'confirm_inquiry_mailer'
  get "inquiry_mailer/done",:to => "inquiry_mailer#done",as: 'done_inquiry_mailer'

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  attachment :icon_image

  geocoded_by :address
  after_validation :geocode
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers:[:google_oauth2]
  
  before_create :build_default_profile
    
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :profile
  has_many :favorites, dependent: :destroy
  has_many :favorite_comments, through: :favorites, source: 'comment'
  
  accepts_nested_attributes_for :profile

  validates :name, 
    uniqueness: { case_sensitive: :false },
    length: { minimum: 4, maximum: 20 }, 
    :presence => true

  def self.from_omniauth(auth)
    find_or_initialize_by(provider: auth["provider"], uid: auth["uid"]) do |user|
        user.provider = auth["provider"]
        user.uid = auth["uid"]
        user.name = auth["info"]["name"]
        user.email = auth["info"]["email"]
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"]) do |user|
        user.attributes = params
      end
    else
      super
    end
  end

  #パスワードのバリデーション実行条件(uidがあれば実行)
  def password_required?
    if uid.present?
      false
    else
      super
    end      
  end

  def self.guest
    find_or_create_by!(email: 'guest@test.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザ"
    end
  end
  
  private
  def build_default_profile
      build_profile
      true
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"].except("extra"))
    # @user = true
    if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user
    else
        session["devise.user_attributes"] = @user.attributes
        redirect_to new_user_registration_url
    end
  end

  def failure
    flash[:notice] ='認証できませんでした'
    redirect_to root_path
  end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_user, only: :create

  def ensure_normal_user
    if params[:user][:email].downcase == 'guest@test.com'
      redirect_to new_user_session_path, alert: 'ゲストユーザーのパスワード再設定はできません。'
    end
  end

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  before_action :set_user_id, only: [:show, :edit, :update,:posts_show, :favorite_comments_show, :best_comments_show]

  def show
    
    @best_comments = Comment.where(best_flag: true).where(user_id: @user.id)
    # いいねした数用
    @to_favorites = Favorite.where(user_id: @user.id)

    # いいねされた数用
    user_comments = Comment.where(user_id: @user.id)
    @get_favorite_count = 0
    user_comments.each do |comment|
      @get_favorite_count += Favorite.where(comment_id: comment.id).count
    end

    @user_posts = Post.where(user_id: @user.id).page(params[:page]).per(5)
    @user_posts_count = Post.where(user_id: @user.id).count

    @user_favorite_comments_count = @user.favorite_comments.includes(:user).count
    @user_best_comments_count = @user.comments.where(best_flag: true).count

  end

  def edit
  end

  def update
    profile = Profile.find(params[:id])
    if profile.update(profile_params)
      redirect_to action: :show,notice: '編集しました'
    else
      render :show
    end
  end

  def posts_show
    @user_posts = Post.where(user_id: @user.id).page(params[:page]).per(5)
    @user_posts_count = Post.where(user_id: @user.id).count
  end

  def favorite_comments_show
    @user_favorite_comments = @user.favorite_comments.includes(:user).page(params[:page]).per(5)
    @user_favorite_comments_count = @user.favorite_comments.includes(:user).count
  end

  def best_comments_show
    @user_best_comments = @user.comments.where(best_flag: true).page(params[:page]).per(5)
    @user_best_comments_count = @user.comments.where(best_flag: true).count
  end

  def set_user_id
    @profile = Profile.find(params[:id])
    @user = User.find(@profile.user_id)
  end

  def profile_params
    params.require(:profile).permit(:introduce,:hp_url,:address,:icon_image) 
  end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :ensure_normal_user, only: %i[update destroy]

  def ensure_normal_user
    if resource.email == 'guest@test.com'
      redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません。'
    end
  end

  # # GET /resource/sign_up
  # def new
  #   @user = User.new
  #   @profile = @user.build_profile
  #   binding.pry
  # end

  #google認証時登録はパスワード入力なし
  # # POST /resource
  def create
    if params[:user][:password].nil?
      generated_password = Devise.friendly_token.first(8)
      uid=session["devise.user_attributes"]["uid"]
      provider=session["devise.user_attributes"]["provider"]
      user = User.new(email: params[:user][:email], password: generated_password, name: params[:user][:name],uid: uid, provider: provider)
      if user.save
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect user
      else
        super
      end
    else
      super
    end
  end

  # # GET /resource/edit
  # def edit
  #   super
  # end

  # # PUT /resource
  # def update
  #   super
  # end

  # # DELETE /resource
  # def destroy
  #   super
  # end

  # # GET /resource/cancel
  # # Forces the session data which is usually expired after sign
  # # in to be expired now. This is useful if the user wants to
  # # cancel oauth signing in/up in the middle of the process,
  # # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  # private

  # def user_params
  #   params.permit(:sign_up, keys: [:email,:encrypted_password,:name])
  # end

  # password = Devise.friendly_token.first(7)
  # if session[:provider].present? && session[:uid].present?
  #   @user = User.create(nickname:session[:nickname], email: session[:email], password: "password", password_confirmation: "password", f_name_kana: session[:f_name_kana],l_name_kana: session[:l_name_kana], f_name_kanji: session[:f_name_kanji], l_name_kanji: session[:l_name_kanji], birthday: session[:birthday], tel: params[:user][:tel])
  #   sns = SnsCredential.create(user_id: @user.id,uid: session[:uid], provider: session[:provider])
  # else
  #   @user = User.create(nickname:session[:nickname], email: session[:email], password: session[:password], password_confirmation: session[:password_confirmation], f_name_kana: session[:f_name_kana],l_name_kana: session[:l_name_kana], f_name_kanji: session[:f_name_kanji], l_name_kanji: session[:l_name_kanji], birthday: session[:birthday], tel: params[:user][:tel])
  # end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
  
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/users/profiles/_best_comment_lists.html.erb
<h4 class="card-title">ベストコメント一覧（全<%= user_best_comments_count %>件）</h4>
  <p class="card-text">
    <% user_best_comments.each do |comment| %>
      <div class="row">
       <%= image_pack_tag 'crown.png',:size =>'60x60' %><br>
        <div class="col-md-12 text_overflow text-left">
          <%= link_to comment.body,post_path(comment.post_id),class: "text-muted" %>
          <div class="text-muted"><%= comment.created_at.strftime("%Y-%m-%d %H:%M") %></div>
        </div>
      </div>
      </p>
      <hr/>
    <% end %>
  </p>
<%= paginate user_best_comments,remote: true %>

app/views/users/profiles/_comment_lists.html.erb
<h4 class="card-title">いいねしたコメント一覧（全<%= user_favorite_comments_count %>件）</h4>
  <p class="card-text">
    <% user_favorite_comments.each do |comment| %>
      <div class="row">
        <div class="col-md-2 text-right">
          <%= link_to users_profile_path(comment.user_id) do %>
            <% if comment.user.profile.icon_image == nil %>
              <%= image_pack_tag 'no_image.jpg', size: '60x60', class: "rounded-circle pull-left profile-thumb" %>
            <% else %>
              <%= attachment_image_tag(comment.user.profile, :icon_image, :fill, 60, 60, class: "rounded-circle pull-left profile-thumb") %>
            <% end %> 
            <br>
            <div class="mt-2 font-weight-bold"><%= comment.user.name %></div>
          <% end %>
        </div>
        <div class="col-md-10 text_overflow text-left">
          <%= link_to comment.body,post_path(comment.post_id),class: "text-muted" %>
          <div class="text-muted"><%= comment.created_at.strftime("%Y-%m-%d %H:%M") %></div>
        </div>
      </div>
      </p>
      <hr/>
    <% end %>
  </p>
<%= paginate user_favorite_comments,remote: true %>

app/views/users/profiles/_post_lists.html.erb
<h4 class="card-title">投稿一覧（全<%= user_posts_count %>件）</h4>
  <p class="card-text">
    <% user_posts.each do |post| %>
      <%= render 'posts/tag_list', tag_list: post.tag_list %><br>
      <span class="font-weight-bold"><%= link_to post.title,post_path(post.id) %></span>
      <% if post.status==false %>
        <div class="post_ended_tag font_size5">
              CLOSE
            </div><br>
      <% end %>
        <p class="text_overflow text-muted"><%= post.body %></p>
        <i class="far fa-comment-dots" aria-hidden="true" style="color: gray;"></i> <%= post.comments.count %>
        <br><%= post.created_at.strftime("%Y-%m-%d %H:%M") %>
      <hr/>
    <% end %>
  </p>
  <%= paginate user_posts,remote: true %>

app/views/users/profiles/_post_lists2.html.erb
<h4 class="card-title">投稿一覧（全<%= user_posts_count %>件）</h4>
  <p class="card-text">
    <% user_posts.each do |post| %>
      <%= render 'posts/tag_list', tag_list: post.tag_list %><br>
      <span class="font-weight-bold"><%= link_to post.title,post_path(post.id) %></span>
      <% if post.status==false %>
        <div class="post_ended_tag font_size5">
              CLOSE
        </div><br>
      <% end %>
        <p class="text_overflow text-muted"><%= post.body %></p>
        <i class="far fa-comment-dots" aria-hidden="true" style="color: gray;"></i> <%= post.comments.count %>
        <br><%= post.created_at.strftime("%Y-%m-%d %H:%M") %>
      <hr/>
    <% end %>
  </p>
  <%= paginate user_posts %>

app/views/users/profiles/best_comments_show.js.erb
$('#lists').html("<%= j(render partial: 'users/profiles/best_comment_lists', locals: {user_best_comments: @user_best_comments,user_best_comments_count: @user_best_comments_count}) %>");

app/views/users/profiles/edit.html.erb
<div class="container mt-4">
<%= form_for(@profile,url: users_update_profile_path(@profile)) do |f| %>

  <!-- devise関係は後で調べる -->
 <div class="form-inline account_border">
 <div class="account_titile">アカウント情報</div>
  <div class="form-group mr-5">
    <%= f.label :name, 'Name',class:'account_text' %>
    <div class="account_data"><%= @user.name %></div>
  </div>
  
  <div class="form-group">
    <%= f.label :email, 'Email',class:'account_text' %>
    <div class="account_data"><%= @user.email %></div>
  </div>
 </div>

  アカウント情報編集は<%= link_to "こちら", edit_user_registration_path %>

  <div class="form-group mt-3">
      <% if @profile.icon_image == nil %>
        <%= image_pack_tag 'no_image.jpg', size: '150x150', class: "rounded-circle pull-left profile-thumb" %>
      <% else %>
        <%= attachment_image_tag(@profile, :icon_image, :fill, 200, 200, class: "rounded-circle pull-left profile-thumb") %>
      <% end %> 
    <br/>
    <%= f.attachment_field :icon_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
  </div>

  <div class="form-group">
    <%= f.label :introduce, '自己紹介（255文字未満）' %>
    <%= f.text_area :introduce, :maxlength => "255", :size => "80x5",  class: 'form-control'  %>
  </div>

  ※以下、店舗情報
  <div class="form-group">
    <%= f.label :hp_url, '店舗サイトURL' %>
    <%= f.text_field :hp_url, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :address, '店舗住所' %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>
  
  <div class="al-c"><%= f.submit 'プロフィール編集を完了する', class: 'btn btn-primary' %></div>
<% end %>
</div>

app/views/users/profiles/favorite_comments_show.js.erb
$('#lists').html("<%= j(render partial: 'users/profiles/comment_lists', locals: {user_favorite_comments: @user_favorite_comments,user_favorite_comments_count: @user_favorite_comments_count}) %>");

app/views/users/profiles/posts_show.js.erb
$('#lists').html("<%= j(render partial: 'users/profiles/post_lists', locals: {user_posts: @user_posts,user_posts_count: @user_posts_count}) %>");

app/views/users/profiles/show.html.erb
<div class="container mt-4">
<div class="row">
<!-- ユーザー情報部分（ページ左） -->
  <aside class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body al-c">
        <div class="profile_name">
          <% if @profile.icon_image == nil %>
            <%= image_pack_tag 'no_image.jpg', size: '150x150', class: "rounded-circle pull-left profile-thumb" %>
          <% else %>
            <%= attachment_image_tag(@profile, :icon_image, :fill, 200, 200, class: "rounded-circle pull-left profile-thumb") %>
          <% end %> 
          <br>
        <div class="mt-2 font-weight-bold"><%= @user.name %></div>
        </div>
        
        <!-- email表示とユーザー情報編集ボタン（current_user時） -->
        <% if user_signed_in? && (@user.id==current_user.id) %>
          <p>登録email:<%= @user.email %></span></p>
          <div class="dropdown mb-3">
            <button class="btn btn-secondary dropdown-toggle edit_drop"
                    type="button" id="dropdownMenu1" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
              ユーザー情報編集
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <%= link_to "アカウント", edit_user_registration_path, class: 'dropdown-item' %>
              <%= link_to "プロフィール", users_edit_profile_path(current_user.id), class: 'dropdown-item' %>
            </div>
          </div>
        <% end %>

        <% if @profile.introduce? %>
          <div class="mb-1">
            <%= Rinku.auto_link(simple_format(@profile.introduce), :all, 'target="_blank"').html_safe %>
          </div>
        <% end %>

        <!-- 投稿、ベストコメント、いいね数表示（横並びにしてアイコン表示にしたい） -->
        <div>
          <br><i class="far fa-comment" aria-hidden="true"></i> <%= link_to @user_posts_count,users_posts_show_path(@user), remote: true %>
          <br><i class="fas fa-crown" aria-hidden="true"></i> <%= link_to @user_best_comments_count,users_best_comments_show_path(@user), remote: true %>
          <br><i class="far fa-heart" aria-hidden="true" style="color: red;"></i>いいねした数：<%= link_to @to_favorites.count,users_favorite_comments_show_path(@user), remote: true %>
          <br><i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>いいねもらった数：<%= @get_favorite_count %>
        </div>
        <hr/>

        <p>店舗サイト</p>
        <% if @profile.hp_url? %>
          <p><%= raw Rinku.auto_link(simple_format(@profile.hp_url), :all, 'target="_blank"') %></p>
        <% else %>
          <p>未設定</p>
        <% end %>

        <p>店舗住所</p>
          <% if @profile.address? %>
            <p><%= @profile.address %></p>

            <!-- 店舗地図表示 -->
            <style>
              #map { height: 300px;}
              </style>
              <script src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials.google[:api_key] %>&callback=initMap" async defer></script>
              <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
              <script src="//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" type="text/javascript"></script>
              <div id="map"></div>
              <script>
                function initMap() {
                  var latlng = new google.maps.LatLng(
                    <%= @profile.latitude %>,
                    <%= @profile.longitude %>
                    );
                  var map = new google.maps.Map(document.getElementById('map'), {
                    zoom: 12,
                    center: latlng
                  });
                  var marker = new google.maps.Marker({
                    position: latlng,
                    map: map
                  });
                  var infowindow = new google.maps.InfoWindow({
                    content: '<a href="https://www.google.com/maps/search/?api=1&query=<%= @profile.latitude %>,<%= @profile.longitude %>" target="_blank" rel="noopener noreferrer">google mapで開く</a>',
                  });
                  infowindow.open(map, marker);
                  google.maps.event.addListener(infowindow, "closeclick", function() {
                    google.maps.event.addListenerOnce(marker, "click", function(event) {
                      infowindow.open(map, marker);
                    });
                  });
                }
                initMap();
              </script>
          <!-- 店舗住所未設定 -->
          <% else %>
            <p>未設定</p>
          <% end %>

      </div>
    </div>
  </aside>

<!-- 一覧部分（ページ右） -->
  <div class="col-md-8">
    <div class="card">
      <div class="card-body" id="lists">
        <%= render 'users/profiles/post_lists2', user_posts: @user_posts,user_posts_count: @user_posts_count %>
      </div>
    </div>
  </div>

</div>
</div>