config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "posts#index"
  resources :posts

  namespace :home do
    get "about", as: 'about'
    get "terms", as: 'terms'
    get "privacy", as: 'privacy'
  end
  
  resources :posts do
    post "select_best_comment", :to => "posts#select_best_comment", as: 'select_best_comment'
    resources :comments,only: [:new, :create, :edit, :update] do
      patch "delete", :to => "comments#delete", as: 'delete'
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
  end

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :omniauth_callbacks => 'users/omniauth_callbacks',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  namespace :users do
    get ":id/profile", :to => "profiles#show", as: 'profile'
    get ":id/profile/edit", :to => "profiles#edit", as: 'edit_profile'
    patch ":id/profile/update", :to => "profiles#update", as: 'update_profile'
    get ":id/profile/posts_show", :to => "profiles#posts_show", as: 'posts_show'
    get ":id/profile/favorite_comments_show", :to => "profiles#favorite_comments_show", as: 'favorite_comments_show'
    get ":id/profile/best_comments_show", :to => "profiles#best_comments_show", as: 'best_comments_show'
  end

  get "inquiry_mailer/new", :to => "inquiry_mailer#new", as: 'new_inquiry_mailer'
  get "inquiry_mailer/confirm",:to => "inquiry_mailer#confirm",as: 'confirm_inquiry_mailer'
  get "inquiry_mailer/done",:to => "inquiry_mailer#done",as: 'done_inquiry_mailer'

end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :best_flag, inclusion: { in: [true, false] }
  validates :delete_flag, inclusion: { in: [true, false] }
  validates :body, presence: true, length: { maximum: 500 }
  validates :post, presence: true
  validates :user, presence: true

  belongs_to :user
  belongs_to :post
  has_many :post_images, dependent: :destroy, foreign_key:'comment_id'
  has_many :favorites, dependent: :destroy
  accepts_attachments_for :post_images, attachment: :image

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end 

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :deadline_post_deleate, only: [:create]
  
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
    @comment.post_images.build
  end

  def create
    @post = Post.find(params[:post_id])
    today=Date.today
    # もし募集期間が過ぎていたらリダイレクト
    if @post.deadline < today
      redirect_to posts_path,notice: 'この投稿はコメント募集終了しています。'
    else
      @comment = Comment.new(comment_params)
      @comment.user_id = current_user.id
      @comment.post_id=@post.id
      if @comment.save
        redirect_to post_path(@post),notice: 'コメントしました'
      else
        render :new
      end
    end

  end

  def edit
    @comment = Comment.find(params[:id])
    @post = Post.find(params[:post_id])
  end

  def update
    @comment = Comment.find(params[:id])
    @post = Post.find(params[:post_id])
    if @comment.update(comment_params)
      # リダイレクト処理
      redirect_to post_path(@post),notice: '編集しました'
    else
      render :edit
    end
  end

  def delete
    @comment = Comment.find(params[:comment_id])
    @post = Post.find(params[:post_id])
    @comment.update(delete_flag: true)
    redirect_to post_path(@post),notice: '編集しました'
  end

  private

  def comment_params
    params.require(:comment).permit(:body,post_images_images: []) 
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<div class="container">
<%= render 'layouts/errors', obj: @comment %>
<div class="d-flex align-items-center">
  <h1>編集</h1>
</div>
<%= form_for [@post,@comment] do |f| %>
  <div class="form-group">
        <%= f.label :body, '投稿内容' %>
        <br/>
        <%= f.text_area :body, class: 'form-control', rows:10 %>
        <small id="content-tip" class="form-text text-muted">
            投稿内容を入力してください。 
        </small>
    </div>
  <div class="form-group">
        <% if @comment.post_images.present? %>
            <% @comment.post_images.each do |image| %>
            <%= attachment_image_tag image, :image, :fill, 200, 200 %>
            <% end %>
        <% end %>
        <br/>
        <%= f.attachment_field :post_images_images, multiple: true %>
        <small id="image-tip" class="form-text text-muted">
        ※複数画像選択可能
        </small>
    </div>
    
    <%= f.submit '編集', class: 'btn btn-info btn-block' %>
    <small id="submit-tip" class="form-text text-muted">
        投稿する前に投稿内容を見直してください!
    </small>
<% end %>
<%= link_to 'コメントを削除', post_comment_delete_path(@post.id,@comment.id),method: :patch, class: 'btn btn-outline-info',data: {confirm: 'コメントを削除しますか?'} %>
</div>

app/views/comments/new.html.erb
<div class="container mt-4">
<%= render 'layouts/errors', obj: @comment %>

<h1>返信</h1>
  <div class="row">
    <div class="col-2 text-right">
      <div class="profile_name">
        <%= link_to users_profile_path(@post.user_id) do %>
          <% if @post.user.profile.icon_image != nil %>
            <%= attachment_image_tag(@post.user.profile, :icon_image, :fill, 40, 40,class: "rounded-circle pull-left profile-thumb") %>
          <% else %>
            <%= image_pack_tag 'no_image.jpg', class: "no_img", size: '60x60', class: "rounded-circle pull-left profile-thumb" %>
          <% end %><br>
            <span style="font-size:10px;"><%= @post.user.name %></span>
        <% end %>
         <br>
      </div>
    </div>
    <div class="col-9 comment_quote">
      <%= @post.body %>
    </div>
  </div>

  <%= form_for [@post,@comment] do |f| %>
    <div class="form-group">
        <%= f.label :body, '投稿内容' %>
        <br/>
        <%= f.text_area :body, class: 'form-control', rows:10 %>
        <small id="content-tip" class="form-text text-muted">
            投稿内容を入力してください。 
        </small>
    </div>
    
    <div class="form-group">
        <% if @comment.post_images.present? %>
            <% @comment.post_images.each do |image| %>
            <%= attachment_image_tag image, :image, :fill, 200, 200 %>
            <% end %>
        <% end %>
        <br/>
        <%= f.attachment_field :post_images_images, multiple: true %>
        <small id="image-tip" class="form-text text-muted">
        ※複数画像選択可能
        </small>
    </div>

    <%= f.submit '返信', class: 'btn btn-info btn-block' %>
    <small id="submit-tip" class="form-text text-muted">
        投稿する前に投稿内容を見直してください!
    </small>
  <% end %>
</div>