config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "posts#index"
  resources :posts

  namespace :home do
    get "about", as: 'about'
    get "terms", as: 'terms'
    get "privacy", as: 'privacy'
  end
  
  resources :posts do
    post "select_best_comment", :to => "posts#select_best_comment", as: 'select_best_comment'
    resources :comments,only: [:new, :create, :edit, :update] do
      patch "delete", :to => "comments#delete", as: 'delete'
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
  end

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :omniauth_callbacks => 'users/omniauth_callbacks',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  namespace :users do
    get ":id/profile", :to => "profiles#show", as: 'profile'
    get ":id/profile/edit", :to => "profiles#edit", as: 'edit_profile'
    patch ":id/profile/update", :to => "profiles#update", as: 'update_profile'
    get ":id/profile/posts_show", :to => "profiles#posts_show", as: 'posts_show'
    get ":id/profile/favorite_comments_show", :to => "profiles#favorite_comments_show", as: 'favorite_comments_show'
    get ":id/profile/best_comments_show", :to => "profiles#best_comments_show", as: 'best_comments_show'
  end

  get "inquiry_mailer/new", :to => "inquiry_mailer#new", as: 'new_inquiry_mailer'
  get "inquiry_mailer/confirm",:to => "inquiry_mailer#confirm",as: 'confirm_inquiry_mailer'
  get "inquiry_mailer/done",:to => "inquiry_mailer#done",as: 'done_inquiry_mailer'

end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_taggable
  validates :title, presence: true,length: { maximum: 100 }
  validates :body, presence: true,length: { maximum: 500 }
  validates :deadline, presence: true
  validates :status, inclusion: { in: [true, false] }
  validates :user, presence: true
  validate :deadline_cannot_be_in_the_past

  belongs_to :user
  has_many :post_images, dependent: :destroy, foreign_key:'post_id'
  has_many :comments, dependent: :destroy
  accepts_attachments_for :post_images, attachment: :image

  def self.search(search,status)
    if search
      if status
        #キーワード入っていてチェックボックス入ってる時（false含め全件取得）
       Post.where(['title LIKE ?', "%#{search}%"])
      else
        #キーワード入っていてチェックボックスチェックない時、trueのみ表示（募集中のみ表示）
       Post.where(['title LIKE ?', "%#{search}%"]).where(status: true)
      end
    else
      if status
        #キーワードなくてチェックある時、全件取得
       Post.all
      else
        #キーワードなくてチェックない時、trueのみ取得（募集中のみ表示）
       Post.where(status: true)
      end
    end
  end

  def self.select_best_comment(best_comment_id,post_id)
    post = Post.find(post_id)
    post.update(best_comment_id: best_comment_id,status: false)
    comment=Comment.find(best_comment_id)
    comment.update(best_flag: true)
  end

  def deadline_cannot_be_in_the_past
    if deadline.present? && deadline < Date.today
      errors.add(:deadline, ": 過去の日付は使用できません")
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :deadline_post_deleate, only: [:index]
  before_action :authenticate_user!, only: [:new,:edit]

  def index
    @posts = Post.search(params[:search],params[:status]).order('updated_at DESC').page(params[:page]).per(6)
    if params[:tag_name]
      @posts = Post.tagged_with("#{params[:tag_name]}").order('updated_at DESC').page(params[:page]).per(6)
    end
  end

  def new
    @post = Post.new
    @post.post_images.build
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to posts_path,notice: '投稿しました'
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
       redirect_to @post,notice: '編集しました'
    else
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path,notice: '削除しました'
  end

  def search
    @posts = Post.search(params[:search])
  end

  def select_best_comment
    @best_comment=Post.select_best_comment(
      params[:post][:best_comment],
      params[:post_id]
    )
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body,:status,:deadline,:tag_list,post_images_images: []) 
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_tag_list.html.erb
<% tag_list.each do |tag| %>
  <span class="badge badge-primary mr-1 p-2">
    <%= link_to tag, posts_path(tag_name: tag),class: "text-white" %>
  </span>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
<%= render 'layouts/errors', obj: @post %>

<div class="d-flex align-items-center mb-4">
  <h1>編集</h1>
</div>
<%= form_for @post do |f| %>
    <div class="form-group">
        <%= f.label :title, '投稿タイトル' %>
        <%= f.text_field :title, class: 'form-control' %>
        <small id="title-tip" class="form-text text-muted">
            タイトルを入力してください（100文字以内）
        </small>
    </div>
    <div class="form-group">
        <%= f.label :body, '投稿内容' %>
        <%= f.text_area :body, class: 'form-control', rows:10 %>
        <small id="content-tip" class="form-text text-muted">
            投稿内容を入力してください。 
        </small>
    </div>

    <div class="form-group">
        <%= f.label :tag_list, 'カテゴリ' %>
        <%= f.text_field :tag_list,value: @post.tag_list.join(','), class: 'form-control' %>
        <small id="content-tip" class="form-text text-muted">
            カテゴリ名をコンマで区切って入力してください。（例：Tシャツ,色）
        </small>
    </div>
    
    <div class="form-group">
    <% if @post.post_images.present? %>
        <% @post.post_images.each do |image| %>
          <%= attachment_image_tag image, :image, :fill, 200, 200 %>
        <% end %>
    <% end %>
    <br/>
    <%= f.attachment_field :post_images_images, multiple: true %>
        <small id="image-tip" class="form-text text-muted">
            ※複数画像選択可能
        </small>
    </div>
    <div class="form-group">
        <%= f.label :deadline, 'コメント募集期間' %>
        <%= f.date_field :deadline, class: 'form-control' %>
        <small id="content-tip" class="form-text text-muted">
            コメント募集期間を指定してください 
        </small>
    </div>

      <%= f.radio_button :status, :true, checked: "checked" %>
      <%= f.label :true,"募集中" %>
      <%= f.radio_button :status, :false %>
      <%= f.label :status,"評価しないで募集終了" %>
    <%= f.submit '編集', class: 'btn btn-info btn-block' %>
    <small id="submit-tip" class="form-text text-muted">
        投稿する前に投稿内容を見直してください!
    </small>
<% end %>
<%= link_to "投稿を削除", post_path(@post.id), method: :delete, class: 'btn btn-outline-info',"data-confirm" => "本当に削除しますか？" %>
</div>

app/views/posts/index.html.erb
<section class="jumbotron text-center">
  <div class="title_text">
      <div>
        <h1 class="jumbotron-heading section_title">FAS</h1>
      </div>
      <div class="full_title">Fashion Advise site</div>
  </div>
</section>

  <div id="notice"><%= notice %></div> 
  <div id="alert"><%= alert %></div>

<div class="container">
 <div class="album py-3 bg-light">
  <div class="container">
    <%= form_tag posts_path, class:"form-inline",:method => 'get' do %>
      <div class="input-group">
        <%= text_field_tag :search, params[:search], placeholder: "タイトル検索",class:"form-control mb-2 mr-sm-2" %>
        <%= button_tag :submit ,:name => nil, id: "sbtn2" do %>
            <i class="fas fa-search" aria-hidden="true"></i>
        <% end %>
      </div>
      <div class="s_check_box">
        <%= check_box_tag :status, checked = true,value=false,class: "ml30px" %>
        <%= label_tag :status, "募集終了も含める" %>
      </div>
    <% end %>

    <div class="d-flex align-items-center">
    <!-- 投稿ボタン -->
      <div class="ml-auto posts_button">
        <% if user_signed_in? %>
        <%= link_to "投稿", new_post_path, class: 'form_button' %>
        <% else %>
        <%= link_to "投稿", new_user_session_path, class: 'form_button' %>
        <% end %>
      </div>
    </div>

   <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">

      <!-- 投稿カード一覧 -->
      <% @posts.each do |post| %>
        <div class="col-xs-12 col-lg-4">
          <div class="card mb-4 shadow-sm">

            <div class="post_index_image">
              <% if post.post_images.first == nil %>
                <a href="/posts/<%= post.id %>">
                  <%= image_pack_tag 'no_photo.jpg', size:'300x300', class: "card-img-top img-fluid" %>
                </a>
              <% else %>
                <a href="/posts/<%= post.id %>">
                  <%= attachment_image_tag(post.post_images.first, :image, :fill, 300, 300, class: "card-img-top img-fluid") %>
                </a>
              <% end %>
              <br/>
              <!-- 募集終了タグ -->
                <% if post.status == false %>
                  <div class="ended">
                    Close
                  </div>
                <% end %>
            </div>

            <div class="card-body posts_card">
              <div class="card-text">
                  <div class="text_overflow">
                    <%= link_to post.title,post_path(post.id),class: "post_title" %>
                  </div>
              </div>

              <div class="justify-content-between align-items-center post_index_tag">
                <i class="fas fa-tags"></i><%= render 'posts/tag_list', tag_list: post.tag_list %>
              </div>

              <div class="row post_data">
                <div class="col-2">
                  <div class="profile_name">
                    <%= link_to users_profile_path(post.user_id) do %>
                      <% if post.user.profile.icon_image == nil %>
                        <%= image_pack_tag 'no_image.jpg', size: '20x20', class: "rounded-circle pull-left profile-thumb" %>
                      <% else %>
                        <%= attachment_image_tag(post.user.profile, :icon_image, :fill, 20, 20, class: "rounded-circle pull-left profile-thumb") %>
                      <% end %>                      
                      <br>
                      <!--<span style="font-size:10px;"><%= post.user.name %></span>-->
                    <% end %>
                  </div>
                </div>

                <div class="col-3 text-center">
                  <small class="text-muted card_comment_icon"><i class="far fa-comment-dots" aria-hidden="true" style="color: gray;"></i> <%= post.comments.count %></small>
                </div>

                <div class="col-7 post_index_time">
                  <small class="text-muted"><%= post.created_at.strftime("%Y-%m-%d") %>
                - <%= post.deadline.strftime("%Y-%m-%d") %></small>
                </div>
              </div>
            </div>
         
         </div>
        </div>
      <% end %>
      <!-- 投稿一覧ループ終了 -->

      </div>
      <!-- ページネーション -->
      <%= paginate @posts %>
    </div>
   </div>
  </div>
 </div>
</div>

app/views/posts/new.html.erb
<div class="container">
<%= render 'layouts/errors', obj: @post %>

<div class="d-flex align-items-center mb-4">
  <h1>投稿</h1>
  <div class="ml-auto posts_button">
      <%= link_to '投稿一覧', posts_path, class: 'btn btn-outline-secondary' %>
  </div>
</div>

<%= form_for @post do |f| %>
    <div class="form-group">
        <%= f.label :title, '投稿タイトル' %>
        <%= f.text_field :title, class: 'form-control' %>
        <small id="title-tip" class="form-text text-muted">
            タイトルを入力してください（100文字以内）
        </small>
    </div>
    <div class="form-group">
        <%= f.label :body, '投稿内容' %>
        <%= f.text_area :body, class: 'form-control', rows:10 %>
        <small id="content-tip" class="form-text text-muted">
            投稿内容を入力してください。 （500文字）
        </small>
    </div>

    <div class="form-group">
        <i class="fas fa-tags"></i><%= f.label :tag_list, 'カテゴリ' %>
        <%= f.text_field :tag_list,value: @post.tag_list.join(','), class: 'form-control' %>
        <small id="content-tip" class="form-text text-muted">
            カテゴリ名をコンマで区切って入力してください。（例：Tシャツ,色）
        </small>
    </div>


    <div class="form-group">
        <% if @post.post_images.present? %>
            <% @post.post_images.each do |image| %>
            <%= attachment_image_tag image, :image, :fill, 200, 200 %>
            <% end %>
        <% end %>
        <br/>
        <%= f.attachment_field :post_images_images, multiple: true %>
        <small id="image-tip" class="form-text text-muted">
        ※複数画像選択可能
        </small>
    </div>
    
    <div class="form-group">
        <%= f.label :deadline, 'コメント募集期間' %>
        <%= f.date_field :deadline, class: 'form-control' %>
        <small id="content-tip" class="form-text text-muted">
            コメント募集期間を指定してください 
        </small>
    </div>
    <%= f.submit '投稿', class: 'btn btn-info btn-block' %>
    <small id="submit-tip" class="form-text text-muted">
        投稿する前に投稿内容を見直してください!
    </small>
<% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
<div class="d-flex align-items-center mb-4">
    <div class="ml-auto posts_button">
        <% if user_signed_in? && (current_user.id==@post.user_id) %>
          <%= link_to "編集", edit_post_path, class: 'btn btn-outline-info' %>
        <% end %>
    </div>
</div>

<!-- 投稿部分 -->
<div class="card show_card">
  <div class="card-header bg-white">
      <h3>
        <%= @post.title %>
        <!-- コメント募集終了タグ -->
        <% if !@post.status %>
            <div class="post_ended_tag">
              CLOSE
            </div>
        <% end %>
      </h3>
      <!-- カテゴリタグ -->
      <i class="fa fa-tags" aria-hidden="true" style="color: gray;"></i><%= render 'posts/tag_list', tag_list: @post.tag_list %>
  </div>
  <div class="card-body">
    <p class="card-text">
      <%= Rinku.auto_link(simple_format(@post.body), :all, 'target="_blank"').html_safe %>
    </p>

      <% if @post.post_images.present? %>
        <% @post.post_images.each do |image| %>
          <%= attachment_image_tag image, :image, :fill, 200, 200 %>
        <% end %>
      <% end %>
    <!-- 投稿がコメント募集中だったら、返信ボタン表示 -->
    <% if @post.status == true %>
      <div class="text-right">
      <% if user_signed_in? %>
        <% unless (current_user.id==@post.user_id) %>
            <%= link_to "返信する", new_post_comment_path(@post.id), class: 'btn btn-outline-info' %>
        <% end %>
      <% else %>
        <%= link_to "ログインして返信する", new_user_session_path, class: 'btn btn-outline-info' %>
      <% end %>
      </div>
    <% end %>

      <div class="mt-3">
        <div class="row">
          <div class="col-8 text-right">
            <div class="profile_name">
              <%= link_to users_profile_path(@post.user_id) do %>
                <div class="profile_name">
                  <% if @post.user.profile.icon_image == nil %>
                    <%= image_pack_tag 'no_image.jpg', size: '60x60', class: "rounded-circle pull-left profile-thumb" %>
                  <% else %>
                    <%= attachment_image_tag(@post.user.profile, :icon_image, :fill, 60, 60, class: "rounded-circle pull-left profile-thumb") %>
                  <% end %> 
                  <br>
                  <div class="mt-2 font-weight-bold"><%= @post.user.name %></div>
                </div>
              <% end %>
            </div>
          </div>

          <div class="col post_show_time flex-column">
            <% if @post.created_at != @post.updated_at  %>
              <div class="text-info">
              更新： <%= @post.updated_at.strftime("%Y-%m-%d %H:%M") %>
              </div>
            <% end %>
            <div>
              投稿： <%= @post.created_at.strftime("%Y-%m-%d %H:%M") %>
            </div>
          </div>

          <div class="col post_show_time">
            募集締切： <%= @post.deadline.strftime("%Y-%m-%d") %>
          </div>
        </div>
      </div>
  </div>
</div>
<!-- 投稿部分終了 -->

<div style="margin:30px 30px;">
<!-- コメント部分開始 -->
  <div class="border-bottom mb-3">回答<%= @comments.count %> 件</div>

<!-- ベストコメントフォームループ -->
  <%= form_with(model: @post,url: "#{@post.id}/select_best_comment", method: 'post', local: true) do |form| %>
    <!-- コメントループ -->
    <% @comments.each do |comment| %>
      <% if !comment.delete_flag %>
        <% if @post.best_comment_id==comment.id %>
            ベストコメント
            <%= image_pack_tag 'crown.png',:size =>'60x60' %>
            <br/>
        <% end %>

        <div class="row">
          <div class="col-md-2 text-center">
            <div class="select_best_cimment">
              <% if (user_signed_in?)&&(current_user.id==@post.user_id) && (@post.status==true) %>
                <%= form.radio_button :best_comment, comment.id %>
                <%= form.label :best_comment, "ベストコメントに選ぶ", {value: comment.id, style: "display: inline-block;"} %>
              <% end %>
            </div>

	          <div class="profile_name">
            	<%= link_to users_profile_path(comment.user_id) do %>
                <% if comment.user.profile.icon_image == nil %>
                  <%= image_pack_tag 'no_image.jpg', size: '80x80', class: "rounded-circle pull-left profile-thumb" %>
                <% else %>
                  <%= attachment_image_tag(comment.user.profile, :icon_image, :fill, 80, 80, class: "rounded-circle pull-left profile-thumb") %>
                <% end %> 
                <br>
                <div class="mt-2 font-weight-bold"><%= comment.user.name %></div>
            	<% end %>
            </div>
          </div>
          <div class="col-md-8">
            <%= Rinku.auto_link(simple_format(comment.body), :all, 'target="_blank"').html_safe %>
          </div>
          <div class="col-md-2">
            <div class="text-muted"><%= comment.created_at.strftime("%Y-%m-%d %H:%M") %></div>
          </div>
        </div>
        </p>

        <% if comment.post_images.present? %>
          <% comment.post_images.each do |image| %>
            <%= attachment_image_tag image, :image, :fill, 200, 200 %>
          <% end %>
        <% end %>
        <br/>
          <!-- いいね機能 -->
        <p>
        <% if (user_signed_in?)&&(current_user.id!=comment.user_id) %>
          <% if comment.favorited_by?(current_user) %>
            <li class="favorite-list">
                <%= link_to post_comment_favorites_path(comment.post_id,comment.id), method: :delete do %>
                <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                <%= comment.favorites.count %>
                <% end %>
            </li>
            <% else %>
            <li class="favorite-list">
                <%= link_to post_comment_favorites_path(comment.post_id,comment.id), method: :post do %>
                <i class="far fa-heart" aria-hidden="true" style="color: red;"></i>
                <%= comment.favorites.count %>
                <% end %>
            </li>
          <% end %>
        <% else %>
          <li class="favorite-list">
            <i class="far fa-heart" aria-hidden="true" style="color: red;"></i>
          <%= comment.favorites.count %>
        <% end %>
        </p>
          
          <% if (user_signed_in?) && (current_user.id==comment.user_id) %>
            <div class="text-right">
              <%= link_to "編集", edit_post_comment_path(@post.id,comment.id), class: 'btn btn-outline-info' %>
            </div>
          <% end %>

        <!-- コメント削除されていたら、削除ページ表示 -->
      <% else %>
        <div class="row">
          <div class="col-md-2 text-center">
           <div class="profile_name">
            <%= link_to users_profile_path(comment.user_id) do %>
              <% if comment.user.profile.icon_image == nil %>
                <%= image_pack_tag 'no_image.jpg', size: '80x80', class: "rounded-circle pull-left profile-thumb" %>
              <% else %>
                <%= attachment_image_tag(comment.user.profile, :icon_image, :fill, 80, 80, class: "rounded-circle pull-left profile-thumb") %>
              <% end %> 
              <br>
              <div class="mt-2 font-weight-bold"><%= comment.user.name %></div>
            <% end %>
           </div>
          </div>
          <div class="col-md-8">
            <span class="border border-danger">このコメントは削除されました。</span>
          </div>
          <div class="col-md-2">
            <div class="text-muted"><%= comment.created_at.strftime("%Y-%m-%d %H:%M") %></div>
          </div>
        </div>
      <% end %>
      <hr style="margin-bottom:30px;">
    <% end %>

    <% if user_signed_in? && (current_user.id==@post.user_id) && (@post.status==true) && (@post.comments.present?) %>
      <%= form.submit 'ベストコメントを決定する', class: 'btn btn-info btn-block' %>
    <% end %>
              <br/>
  <% end %>
</div>
</div>