config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "posts#index"
  resources :posts

  namespace :home do
    get "about", as: 'about'
    get "terms", as: 'terms'
    get "privacy", as: 'privacy'
  end
  
  resources :posts do
    post "select_best_comment", :to => "posts#select_best_comment", as: 'select_best_comment'
    resources :comments,only: [:new, :create, :edit, :update] do
      patch "delete", :to => "comments#delete", as: 'delete'
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
  end

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :omniauth_callbacks => 'users/omniauth_callbacks',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  namespace :users do
    get ":id/profile", :to => "profiles#show", as: 'profile'
    get ":id/profile/edit", :to => "profiles#edit", as: 'edit_profile'
    patch ":id/profile/update", :to => "profiles#update", as: 'update_profile'
    get ":id/profile/posts_show", :to => "profiles#posts_show", as: 'posts_show'
    get ":id/profile/favorite_comments_show", :to => "profiles#favorite_comments_show", as: 'favorite_comments_show'
    get ":id/profile/best_comments_show", :to => "profiles#best_comments_show", as: 'best_comments_show'
  end

  get "inquiry_mailer/new", :to => "inquiry_mailer#new", as: 'new_inquiry_mailer'
  get "inquiry_mailer/confirm",:to => "inquiry_mailer#confirm",as: 'confirm_inquiry_mailer'
  get "inquiry_mailer/done",:to => "inquiry_mailer#done",as: 'done_inquiry_mailer'

end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger" role="alert">
    <div id="error_explanation">
      <h3><strong>入力内容にエラーがあります。</strong></h3>

      <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="mainfooter" role="contentinfo">
  <div class="footer-middle">
  <div class="container">


  <div class="row">
		<div class="col-md-12 footer_border">
			<!--<p class="text-center">&copy; Copyright 2020 - FAS.inc</p>-->
		</div>
	</div>

    <div class="row">
      <div class="col-md-4 text-center">
        <!--Column1-->
        <div class="footer-pad">
          <!--<h4>Heading 2</h4>-->
          <ul class="list-unstyled">
            <li><%= link_to "利用規約", home_terms_path %></li>
          </ul>
        </div>
      </div>
      <div class="col-md-4 text-center">
        <!--Column1-->
        <div class="footer-pad">
          <!--<h4>Heading 3</h4>-->
          <ul class="list-unstyled">
            <li><%= link_to "プライバシーポリシー", home_privacy_path %></li>
          </ul>
        </div>
      </div>
    	<div class="col-md-4 text-center">
    		<!--<h4>Follow Us</h4>-->
            <ul class="social-network social-circle">
             <li><a href="https://ja-jp.facebook.com/" class="icoFacebook" title="Facebook" target="_blank" rel="noopener noreferrer"><i class="fab fa-facebook" ></i></a></li>
             <li><a href="https://www.instagram.com/" class="icoLinkedin" title="Instagram" target="_blank" rel="noopener noreferrer"><i class="fab fa-instagram"></i></a></li>
             <li><a href="https://twitter.com" class="icoTwitter" title="Twitter" target="_blank" rel="noopener noreferrer"><i class="fab fa-twitter"></i></a></li>
            </ul>				
		</div>
    </div>
	<div class="row">
		<div class="col-md-12 copy">
			<p class="text-center">&copy; Copyright 2021 - FAS.inc</p>
		</div>
	</div>


  </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark">
  <a class="navbar-brand logo" href="/">FAS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse main_nav" id="navbarCollapse">
    <div class="navbar-nav mr-auto">
    </div>
    <ul class="navbar-nav navbar-right">
      <li class="nav-item <%= 'active' if current_page?(root_path) %>">
        <%= link_to "Home", root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(home_about_path) %>">
        <%= link_to "About", home_about_path, class: 'nav-link' %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(new_inquiry_mailer_path) %>">
        <%= link_to "Contact", new_inquiry_mailer_path, class: 'nav-link' %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(new_user_session_path) %>">
        <%= link_to "Sign In", new_user_session_path, class: 'nav-link' %>
      </li>
    </ul>
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>FAS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'js_file/script' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@300;700&family=Julius+Sans+One&family=Lato:wght@300&display=swap" rel="stylesheet">
    <%= favicon_pack_tag('favicon.svg') %>
  </head>

  <body>
    <div id="wrapper">
      <div class="container mt-5">
        <% unless user_signed_in? %>
          <%= render partial: 'layouts/header' %>
        <% else %>
          <%= render partial: '/users/header' %>
        <% end %>
      </div>

        <% unless current_page?(root_path) || current_page?(posts_path) %>
         <div class="container alert_notice">
          <div id="notice"><%= notice %></div> 
          <div id="alert"><%= alert %></div>
         </div>
        <% end %>
      
      <%= yield %>
      
        <%= render partial: 'layouts/footer' %>
    </div>

    <span id="top">
      <a href="#">
        <i class="fas fa-arrow-circle-up fa-3x top_arrow"></i>
      </a>
    </span>

  </body>
</html>